  apiVersion: eksctl.io/v1alpha5
  kind: ClusterConfig

  metadata:
    name: stockinfo-app
  region: eu-central-1
  version: "1.27"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: stockinfo-policy
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/AmazonRDSFullAccess"
        - "arn:aws:iam::636970537472:policy/rds-connect"
        - "arn:aws:iam::aws:policy/AdministratorAccess"

vpc:
  subnets:
    private:
      eu-central-1f: { id: subnet-0bf22a8f71d31b5d6 }
      eu-central-1c: { id: subnet-0d637573e65b852ad }
      eu-central-1d: { id: subnet-0675f36dd81b81857 }
    public:
      eu-central-1a: { id: subnet-0d7cbc240162e7bf6 }
      eu-central-1b: { id: subnet-070c05a0840fe00c1 }

managedNodeGroups:
  - name: stockinfo-ng
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    instanceType: t2.small
    ssh:
      enableSsm: true

cloudWatch:
  clusterLogging:
    enableTypes: [ "*" ]