apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockinfo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stockinfo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stockinfo-app
    spec:
      containers:
        - name: stockinfo-app-container
          image: 636970537472.dkr.ecr.eu-central-1.amazonaws.com/stockinfo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080